version: '2'
services:
  web:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - .:/usr/share/nginx/html

  auth:
    image: jboss/keycloak
    ports:
      - 8083:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: keycloak
      DB_VENDOR: h2